# conda env create -f environment.yml
# conda remove -n emg_force_analysis (for windows conda remove --name emg_force_analysis --all
# conda info --envs
name: emg_force_analysis

dependencies:
  - python==3.6.5
  - matplotlib==2.2.2
  - numpy==1.15
  - scipy==1.1.0
  - pandas==0.23.4
  - opencv==3.4.2
  - scikit-learn==0.20.1
  - pywavelets
  - tqdm==4.32.1