# conda env create -f environment.yml
# conda remove --name emg_force_analysis
# conda info --envs
name: emg_force_analysis

dependencies:
  - python==3.6.5
  - matplotlib==2.2.2
  - numpy==1.15
  - scipy==1.1.0
  - pandas==0.23.4